import type { AiProvider } from "@/lib/ai/types";

export const mockAiProvider: AiProvider = {
  name: "mock",
  async extractSchedule(input) {
    if (input.type === "sekolah_sabat") {
      return {
        schedule_type: "sekolah_sabat",
        period: "Triwulan 3 - 2026",
        church: "GMAHK Tidar 2 Surabaya",
        rows: [
          {
            date: "04 Juli 2026",
            date_text: "04 Juli 2026",
            pemimpin_doa_tutup: "Bpk. Agung Wijaya",
            doa_buka_ayat_inti: "Ibu Maria Lestari",
            mision: "Bpk. Joko Sutanto",
            promosi_pp_rumah_tangga: "Bpk. Daniel Purba",
            pembawa_persembahan: "Ibu Martha Sihombing",
            confidence: 0.92,
            notes: "Mock extraction untuk development.",
          },
          {
            date: "11 Juli 2026",
            date_text: "11 Juli 2026",
            pemimpin_doa_tutup: "Ibu Ester Manurung",
            doa_buka_ayat_inti: "Bpk. Tony Han",
            mision: "Ibu Sinta Hutapea",
            promosi_pp_rumah_tangga: null,
            pembawa_persembahan: "Bpk. Mulyono",
            confidence: 0.76,
            notes: "Kolom promosi perlu dikonfirmasi.",
          },
        ],
      };
    }

    return {
      schedule_type: "khotbah",
      period: "Triwulan 3 - 2026",
      church: "GMAHK Tidar 2 Surabaya",
      rows: [
        {
          date: "04 Juli 2026",
          date_text: "04 Juli 2026",
          pianis: "Ibu Grace",
          chorister: "Bpk. David",
          doa_invokasi: "Bpk. Samuel Sinaga",
          ayat_bersahutan: "Mazmur 100:1-5",
          lagu_buka: "LSEL No. 205",
          doa_syafaat: "Ibu Lidya Tambunan",
          persembahan_syukur: "Diaken Bertugas",
          jemaat_memuji: "LSEL No. 18",
          doa_persembahan: "Bpk. Markus Hutabarat",
          jemaat_menyambut: "LSEL No. 341",
          lagu_pujian_1: "Vocal Group Pemuda",
          khotbah_anak: "Ibu Ruth Siregar",
          jemaat_menyanyi: "LSEL No. 341",
          scoreboard_visi_misi: "Tim Multimedia",
          ayat_inti: "Yohanes 15:5",
          lagu_tema: "LSEL No. 322",
          khotbah: "Pdt. Daniel Hutapea",
          tema_khotbah: "Tinggal Di Dalam Kristus",
          lagu_tutup: "LSEL No. 214",
          doa_tutup: "Pdt. Daniel Hutapea",
          komunikasi_jemaat: "Sekretariat Jemaat",
          confidence: 0.9,
          notes: "Mock extraction untuk development.",
        },
        {
          date: "11 Juli 2026",
          date_text: "11 Juli 2026",
          pianis: "Ibu Sarah",
          chorister: "Bpk. Michael",
          doa_invokasi: "Bpk. Andreas Sitorus",
          ayat_bersahutan: "Yesaya 40:28-31",
          lagu_buka: "LSEL No. 12",
          doa_syafaat: "Ibu Naomi Simanjuntak",
          persembahan_syukur: "Diaken Bertugas",
          jemaat_memuji: "LSEL No. 29",
          doa_persembahan: "Bpk. Robert Manalu",
          jemaat_menyambut: "LSEL No. 120",
          lagu_pujian_1: "Paduan Suara Jemaat",
          khotbah_anak: "Ibu Yohana Tampubolon",
          jemaat_menyanyi: "LSEL No. 120",
          scoreboard_visi_misi: "Tim Multimedia",
          ayat_inti: "Roma 8:28",
          lagu_tema: "LSEL No. 198",
          khotbah: "Pdt. Lukas Nainggolan",
          tema_khotbah: "Setia Sampai Akhir",
          lagu_tutup: "LSEL No. 91",
          doa_tutup: "Pdt. Lukas Nainggolan",
          komunikasi_jemaat: "Bpk. Bendry Sitohang",
          confidence: 0.84,
          notes: "Mock extraction untuk development.",
        },
      ],
    };
  },
};
